// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCspxOAFL2OrJIXjA22AUmbwIGyXBXLqco',
    appId: '1:588890714469:web:c9017379843fbcc872718c',
    messagingSenderId: '588890714469',
    projectId: 'ecom-flutterapplication1',
    authDomain: 'ecom-flutterapplication1.firebaseapp.com',
    storageBucket: 'ecom-flutterapplication1.appspot.com',
    measurementId: 'G-3QKJW7NQD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENVbrWBYw5gWNbpwQo5yieCmQuR5TaP8',
    appId: '1:588890714469:android:d4732b21d9ac383c72718c',
    messagingSenderId: '588890714469',
    projectId: 'ecom-flutterapplication1',
    storageBucket: 'ecom-flutterapplication1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-T9eajbo1vquUkoo83yhzZ6KR4yXGxg8',
    appId: '1:588890714469:ios:d4ab8ae508f81e6a72718c',
    messagingSenderId: '588890714469',
    projectId: 'ecom-flutterapplication1',
    storageBucket: 'ecom-flutterapplication1.appspot.com',
    androidClientId: '588890714469-ciahof2e5q7fk4l27q2vt0i6ckvrdptd.apps.googleusercontent.com',
    iosClientId: '588890714469-m7poq784h4nhquvss815ec76h8hsua3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.seller',
  );
}
